FROM andrewosh/binder-base
MAINTAINER Cyril Becot <cyril.becotNOSPAM@cern.ch>
USER root

# Add george & its dependencies
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y libeigen3-dev
RUN pip install --upgrade pip
RUN pip install george

